"use client"
import { useEffect, useMemo, useState } from "react"
import useSWR from "swr"
import { Area, AreaChart, CartesianGrid, Line, XAxis, YAxis } from "recharts"
import { Activity, Bell, Bot, Check, ChevronDown, ExternalLink, Newspaper, RefreshCw, Search, ShieldCheck, Sparkles, Star, TrendingDown, TrendingUp, Zap } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { ChartContainer, ChartTooltip, ChartTooltipContent, type ChartConfig } from "@/components/ui/chart"
import { Input } from "@/components/ui/input"
import { cn } from "@/lib/utils"
import type { Signal, IndicatorRead } from "@/lib/indicators"
import { UserMenu } from "@/components/user-menu"
import { AutomationTerminal } from "@/components/automation/automation-terminal"

const macro=["XU100","XU030","SP500","NASDAQ","DJI","USDTRY","EURTRY","XAUUSD","BRENT"]
const chartConfig={price:{label:"Fiyat",color:"var(--chart-1)"},sma:{label:"HO 20",color:"var(--chart-2)"}} satisfies ChartConfig
const fetcher=(url:string)=>fetch(url).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error);return p})
const fmt=(v?:number)=>Number.isFinite(v)?v!.toLocaleString("tr-TR",{minimumFractionDigits:Math.abs(v!)<0.0001?8:Math.abs(v!)<1?4:2,maximumFractionDigits:Math.abs(v!)<0.0001?8:Math.abs(v!)<1?6:2}):"—"
type Asset={id?:string;symbol:string;name:string;market:"BIST"|"ABD"|"Kripto";rank?:number|null;image?:string|null};type Quote={symbol:string;name:string;price?:number;change?:number;ok:boolean};type News={title:string;source:string;url?:string;publishedAt?:string};type Advice={key:string;label:string;signal:Signal;confidence:number;action:string;invalidation:number;target:number};type Distribution={buy:number;hold:number;sell:number;total:number};type Analyst={rating?:string;score?:number;targetLow?:number;targetMean?:number;targetHigh?:number;analystCount?:number;distribution?:Distribution|null};type Technical={signal:Signal;confidence:number;support:number;resistance:number;values:Record<string,number>;fibonacci:Record<string,number>;breakdown:IndicatorRead[];chart:{date:string;price:number;sma:number}[]};type Data={symbol:string;name:string;market:string;currency:string;price:number;change:number;updatedAt:string;source:string;technical:Technical;advice:Advice[];news:News[];analyst?:Analyst}
type View="terminal"|"automation"|"news";type Rules={support:boolean;resistance:boolean;signal:boolean;news:boolean}
const verdictText={pos:"text-positive",neg:"text-negative",neutral:"text-warning"} as const
function Change({value=0}:{value?:number}){return <span className={cn("inline-flex items-center gap-1 font-mono text-xs font-semibold",value>=0?"text-positive":"text-negative")}>{value>=0?<TrendingUp/>:<TrendingDown/>}{value>=0?"+":""}{fmt(value)}%</span>}
function SignalBadge({signal}:{signal:Signal}){return <Badge variant="outline" className={cn("font-mono",signal.includes("AL")?"border-positive/40 bg-positive/10 text-positive":signal.includes("SAT")?"border-negative/40 bg-negative/10 text-negative":"border-warning/40 bg-warning/10 text-warning")}>{signal}</Badge>}
function RichText({text}:{text:string}){return <div className="space-y-2 text-sm leading-relaxed text-muted-foreground">{text.split("\n").filter(l=>l.trim()).map((line,i)=><p key={i}>{line.split(/(\*\*[^*]+\*\*)/g).map((part,j)=>part.startsWith("**")&&part.endsWith("**")?<strong key={j} className="font-bold text-foreground">{part.slice(2,-2)}</strong>:<span key={j}>{part}</span>)}</p>)}</div>}
function Ticker({quotes}:{quotes:Quote[]}){return <div className="ticker-shell"><div className="ticker-track">{[...quotes,...quotes].map((q,i)=><div className="flex shrink-0 items-center gap-3 px-5" key={`${q.symbol}-${i}`}><span className="text-xs text-muted-foreground">{q.name}</span><span className="font-mono text-xs font-bold">{fmt(q.price)}</span>{q.ok?<Change value={q.change}/>:<span className="text-xs text-negative">Veri yok</span>}</div>)}</div></div>}
function Nav({view,setView}:{view:View;setView:(v:View)=>void}){return <div className="flex gap-1">{([{v:"terminal",t:"Terminal",i:Activity},{v:"automation",t:"Otomasyon",i:Zap},{v:"news",t:"Haberler",i:Newspaper}] as const).map(x=><Button key={x.v} size="sm" variant={view===x.v?"default":"ghost"} onClick={()=>setView(x.v)}><x.i/>{x.t}</Button>)}</div>}
function IndicatorGrid({reads}:{reads:IndicatorRead[]}){return <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{reads.map(r=><div key={r.key} className="rounded-lg border bg-card/60 p-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{r.group}</p><p className={cn("mt-1 text-base font-bold",verdictText[r.verdict])}>{r.title}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{r.note}</p></div>)}</div>}
export function FinanceDashboard(){
 const[selected,setSelected]=useState("TUPRS"),[query,setQuery]=useState(""),[debouncedQuery,setDebouncedQuery]=useState(""),[market,setMarket]=useState<"Tümü"|"BIST"|"ABD"|"Kripto">("Tümü"),[favorites,setFavorites]=useState<string[]>([]),[view,setView]=useState<View>("terminal"),[timeframe,setTimeframe]=useState<"1m"|"5m"|"15m"|"1h"|"1d">("1d"),[capital,setCapital]=useState("100000"),[risk,setRisk]=useState("1"),[rules,setRules]=useState<Rules>({support:true,resistance:true,signal:true,news:true})
 useEffect(()=>{try{setFavorites(JSON.parse(localStorage.getItem("piyasaiq:favorites:v1")??"[]"));const r=JSON.parse(localStorage.getItem("piyasaiq:rules:v2")??"null");if(r)setRules(r)}catch{}},[])
 useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedQuery(query.trim()),350);return()=>window.clearTimeout(timer)},[query])
 const selectedCrypto=selected.startsWith("crypto:")?selected.slice(7):null
 const dataUrl=selectedCrypto?`/api/market?cryptoId=${encodeURIComponent(selectedCrypto)}&interval=${timeframe}`:`/api/market?symbol=${encodeURIComponent(selected)}&interval=${timeframe}`
 const{data:catalog}=useSWR<{assets:Asset[]}>("/api/market?catalog=1",fetcher,{dedupingInterval:60000}),{data:cryptoCatalog,error:cryptoError,isLoading:cryptoLoading}=useSWR<{assets:Asset[]}>(debouncedQuery.length>=2?`/api/market?cryptoSearch=${encodeURIComponent(debouncedQuery)}`:null,fetcher,{keepPreviousData:true,dedupingInterval:30000}),{data,error,isLoading,mutate}=useSWR<Data>(dataUrl,fetcher,{refreshInterval:timeframe==="1m"?15000:timeframe==="5m"?30000:300000,dedupingInterval:timeframe==="1m"?8000:timeframe==="5m"?20000:30000}),{data:globalNews}=useSWR<{news:News[]}>(view==="news"?"/api/market?news=1":null,fetcher,{refreshInterval:300000,dedupingInterval:120000})
 const{data:quotePayload}=useSWR("macro-quotes",()=>fetch("/api/market",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbols:macro})}).then(r=>r.json()),{refreshInterval:300000,dedupingInterval:30000});const quotes:Quote[]=quotePayload?.data??macro.map(symbol=>({symbol,name:symbol,ok:false}))
 const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("tr-TR")
 const assets=useMemo(()=>{
    const q=normalize(query)
    const list=(catalog?.assets??[]).filter(a=>(market==="Tümü"||a.market===market)&&normalize(`${a.symbol} ${a.name}`).includes(q))
    const crypto=debouncedQuery.length>=2&&(market==="Tümü"||market==="Kripto")?(cryptoCatalog?.assets??[]):[]
    const combined=[...list]
    for(const c of crypto){
      if(!combined.some(x=>x.symbol===c.symbol)) combined.push(c)
    }
    return combined.sort((a,b)=>Number(favorites.includes(b.id?`crypto:${b.id}`:b.symbol))-Number(favorites.includes(a.id?`crypto:${a.id}`:a.symbol)))
  },[catalog,cryptoCatalog,debouncedQuery,query,market,favorites])
  function selectAsset(asset:Asset){setSelected(asset.id?`crypto:${asset.id}`:asset.symbol);setQuery("")}
  const autoBody=useMemo(()=>data?JSON.stringify({symbol:data.symbol,market:{...data,macro:quotes.filter(q=>q.ok)},question:`${data.symbol} için şirket odaklı kısa yorum üret. İndikatörleri tek tek sayma; şirketi etkileyen emtia, kur, endeks ve haber başlıklarının olası etkisini kısaca açıkla ve sonda kendi AL/SAT/TUT kararını ver.`}):null,[data,quotes])
  const{data:autoAI,isLoading:aiLoading,mutate:refreshAI}=useSWR<{text:string;source:string}>(data?["auto-analysis",data.symbol,data.updatedAt]:null,()=>fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:autoBody!}).then(r=>r.json()),{revalidateOnFocus:false})
  function favorite(s:string){setFavorites(c=>{const n=c.includes(s)?c.filter(x=>x!==s):[s,...c];localStorage.setItem("piyasaiq:favorites:v1",JSON.stringify(n));return n})}function rule(k:keyof Rules){setRules(c=>{const n={...c,[k]:!c[k]};localStorage.setItem("piyasaiq:rules:v2",JSON.stringify(n));return n})}
  const riskAmount=Number(capital)*Number(risk)/100,stopDistance=data?Math.max(data.price-data.technical.support,data.technical.values.atr,0):0,units=stopDistance?Math.floor(riskAmount/stopDistance):0
  return <main className="min-h-screen bg-background font-sans"><Ticker quotes={quotes}/><header className="sticky top-0 z-20 border-b bg-background/95 backdrop-blur"><div className="flex min-h-14 flex-wrap items-center gap-2 px-3 lg:px-5"><div className="mr-2 flex items-center gap-2"><div className="flex size-8 items-center justify-center rounded-md bg-primary text-primary-foreground"><Activity/></div><b className="text-sm font-bold tracking-tight">Bys<span className="text-primary">Furkan</span></b></div><Nav view={view} setView={setView}/><div className="relative ml-auto hidden w-48 md:block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} className="h-8 pl-9" placeholder="Hisse veya kripto ara"/></div><Button size="icon" variant="ghost" aria-label="Bildirimler"><Bell/></Button><UserMenu/></div></header>
   <div className="finance-grid flex flex-col gap-3 p-3 lg:p-4">
   {view==="news"?<NewsCenter news={globalNews?.news??[]} quotes={quotes} onBack={()=>setView("terminal")}/>:view==="automation"?<AutomationTerminal onBack={()=>setView("terminal")}/>:<>
   <section className="grid gap-3 min-[820px]:grid-cols-[260px_minmax(0,1fr)]"><Card size="sm"><CardHeader className="border-b"><CardTitle>Piyasalar</CardTitle><CardDescription>BIST, ABD ve Kripto (Binance Canlı)</CardDescription><div className="flex flex-wrap gap-1 pt-2">{(["Tümü","BIST","ABD","Kripto"] as const).map(x=><Button key={x} size="sm" variant={market===x?"secondary":"ghost"} onClick={()=>setMarket(x)}>{x}</Button>)}</div><div className="relative mt-2 md:hidden"><Search className="absolute left-3 top-1/2 -translate-y-1/2"/><Input className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Hisse veya kripto ara"/></div></CardHeader><CardContent className="flex max-h-[390px] flex-col overflow-y-auto px-0" aria-live="polite">{cryptoLoading&&debouncedQuery.length>=2&&<p className="p-3 text-xs text-muted-foreground">Kripto kataloğu aranıyor…</p>}{cryptoError&&<p className="p-3 text-xs text-negative">{cryptoError.message}</p>}{!cryptoLoading&&!cryptoError&&query.trim().length>=2&&assets.length===0&&<p className="p-3 text-xs text-muted-foreground">Sonuç bulunamadı.</p>}{assets.map(a=>{const key=a.id?`crypto:${a.id}`:a.symbol;return <div key={key} className={cn("flex items-center border-b",selected===key&&"bg-primary/8")}><button className="p-3" aria-label={`${a.symbol} favori`} onClick={()=>favorite(key)}><Star className={cn(favorites.includes(key)&&"fill-warning text-warning")}/></button><button className="min-w-0 flex-1 py-2 pr-3 text-left" onClick={()=>selectAsset(a)}><div className="flex items-center justify-between gap-2"><b className="truncate font-mono text-xs">{a.symbol}</b><Badge variant="outline">{a.market}</Badge></div><p className="truncate text-xs text-muted-foreground">{a.name}{a.rank?` · #${a.rank}`:""}</p></button></div>})}</CardContent></Card>
   <Card size="sm"><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><CardTitle className="font-mono text-lg">{data?.symbol??selected}</CardTitle>{data&&<SignalBadge signal={data.technical.signal}/>}</div><CardDescription>{data?.name??"Yükleniyor"} · {data?.source??(selectedCrypto?"CoinGecko":"Yahoo Finance")}</CardDescription></div><div className="flex flex-col items-end gap-1.5"><div className="text-right"><b className="font-mono text-xl">{data?.currency==="TRY"?"TL ":data?.currency==="USD"?"$ ":`${data?.currency??""} `}{fmt(data?.price)}</b>{data&&<Change value={data.change}/>}</div><div className="flex items-center gap-0.5 rounded-md border border-border/50 bg-muted/40 p-0.5">{([ { id: "1m", label: "1dk" }, { id: "5m", label: "5dk" }, { id: "15m", label: "15dk" }, { id: "1h", label: "1s" }, { id: "1d", label: "1G" }, ] as const).map(tf => (<button key={tf.id} type="button" onClick={()=>setTimeframe(tf.id)} className={cn("rounded px-2 py-0.5 text-[11px] font-mono font-medium transition-all",timeframe===tf.id?"bg-primary text-primary-foreground shadow-sm font-bold":"text-muted-foreground hover:text-foreground")}>{tf.label}</button>))}</div></div></div></CardHeader><CardContent>{error?<p className="py-20 text-center text-negative">Veri alınamadı: {error.message}</p>:isLoading||!data?<p className="py-20 text-center text-muted-foreground">Güncel veri yükleniyor…</p>:<><ChartContainer config={chartConfig} className="h-[200px] w-full aspect-auto"><AreaChart data={data.technical.chart}><CartesianGrid vertical={false}/><XAxis dataKey="date" tickLine={false} axisLine={false} minTickGap={20}/><YAxis orientation="right" domain={[(minimum:number)=>minimum*.98,(maximum:number)=>maximum*1.02]} width={data?.price && data.price < 0.0001 ? 84 : data?.price && data.price < 1 ? 72 : 58} tickFormatter={fmt}/><ChartTooltip content={<ChartTooltipContent formatter={(value) => <span className="font-mono font-medium text-foreground">{fmt(Number(value))}</span>} />}/><Area dataKey="price" type="monotone" stroke="var(--color-price)" fill="var(--color-price)" fillOpacity={.1}/><Line dataKey="sma" type="monotone" stroke="var(--color-sma)" dot={false}/></AreaChart></ChartContainer><div className="flex flex-wrap items-center gap-2 rounded-md border bg-muted/30 p-2"><b className="text-xs">Genel indikatör</b><SignalBadge signal={data.technical.signal}/><span className="font-mono text-xs">%{data.technical.confidence} güven</span><span className="ml-auto text-xs text-muted-foreground">Destek {fmt(data.technical.support)} · Direnç {fmt(data.technical.resistance)}</span></div><div className="mt-3"><IndicatorGrid reads={data.technical.breakdown}/></div></>}</CardContent></Card></section>
 {data&&<section className="grid gap-3 xl:grid-cols-[minmax(0,1.15fr)_minmax(360px,.85fr)]"><Card size="sm" className="border-ai/40 bg-ai-surface"><CardHeader><div className="flex justify-between gap-3"><div><div className="flex items-center gap-2"><Bot className="text-ai"/><CardTitle>Claude Şirket Yorumu</CardTitle></div><CardDescription>Kısa, şirket odaklı ve net kararlı · indikatör tekrarı değil</CardDescription></div><Button size="sm" variant="outline" onClick={()=>refreshAI()}><RefreshCw/>Yenile</Button></div></CardHeader><CardContent>{aiLoading?<p className="text-sm text-muted-foreground">Claude şirketi etkileyen güncel verileri değerlendiriyor…</p>:<RichText text={autoAI?.text??"Analiz hazırlanamadı."}/>}<p className="mt-3 text-[10px] text-muted-foreground">Kaynak: Yahoo Finance · Model: Claude · Eksik bilanço verisi uydurulmaz · Yatırım tavsiyesi değildir.</p></CardContent></Card><div className="flex flex-col gap-3"><ForecastCard data={data}/></div></section>}
 {data&&<section><AnalystCard data={data}/></section>}
 </>}
 </div></main>
}
function NewsItem({news}:{news:News}){
 const[open,setOpen]=useState(false)
 const{data:summary,isLoading}=useSWR<{summary:string}>(open?["summary",news.url??news.title]:null,()=>fetch("/api/summarize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:news.title,source:news.source,url:news.url})}).then(r=>r.json()),{revalidateOnFocus:false})
 return <div className="rounded-lg border bg-card p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-sm font-medium">{news.title}</p><p className="mt-1 text-xs text-muted-foreground">{news.source}{news.publishedAt?` · ${new Date(news.publishedAt).toLocaleString("tr-TR")}`:""}</p></div>{news.url&&<a href={news.url} target="_blank" rel="noreferrer" aria-label="Habere git" className="shrink-0 text-muted-foreground hover:text-primary"><ExternalLink/></a>}</div><button onClick={()=>setOpen(o=>!o)} className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-ai hover:underline"><Sparkles/>AI kısa özet<ChevronDown className={cn("transition-transform",open&&"rotate-180")}/></button>{open&&<div className="mt-2 rounded-md border border-ai/30 bg-ai-surface p-2 text-xs leading-relaxed text-muted-foreground">{isLoading?"Özet çıkarılıyor…":summary?.summary??"Özet alınamadı."}</div>}</div>
}
function NewsCenter({news,quotes,onBack}:{news:News[];quotes:Quote[];onBack:()=>void}){const featured=quotes.filter(q=>["BRENT","XAUUSD","USDTRY","XU100","SP500"].includes(q.symbol));return <section className="mx-auto w-full max-w-5xl"><div className="mb-4 flex items-center justify-between"><div><h1 className="text-xl font-bold">Piyasa Haber Merkezi</h1><p className="text-sm text-muted-foreground">Emtia, kur ve endeks bağlamıyla kaynaklı haber akışı · her habere AI kısa özet</p></div><Button variant="outline" onClick={onBack}>Terminale dön</Button></div><div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{featured.map(q=><Card key={q.symbol} size="sm" className={cn(q.symbol==="BRENT"&&"border-warning/40 bg-warning/5")}><CardHeader><CardDescription>{q.name}</CardDescription><CardTitle className="font-mono">{fmt(q.price)}</CardTitle><Change value={q.change}/></CardHeader></Card>)}</div><Card size="sm" className="mb-4 border-ai/30 bg-ai-surface"><CardContent className="flex items-start gap-3 p-4"><ShieldCheck className="shrink-0 text-ai"/><div><b className="text-sm">Bugünün bağlam kontrolü</b><p className="text-xs leading-relaxed text-muted-foreground">Haber başlığını tek başına sinyal sayma. Brent, kur ve endeks hareketi aynı yönde teyit veriyorsa şirket etkisi güçlenir; aksi durumda pozisyon boyutunu küçült.</p></div></CardContent></Card><div className="grid gap-3 md:grid-cols-2">{news.length?news.map(n=><NewsItem key={n.url??n.title} news={n}/>):<p className="text-muted-foreground">Haberler yükleniyor…</p>}</div></section>}

function AnalystBar({label,count,total,tone}:{label:string;count:number;total:number;tone:string}){const pct=total?Math.round(count/total*100):0;return <div><div className="mb-1 flex items-center justify-between text-xs"><span className={cn("font-semibold",tone)}>{label}</span><span className="font-mono text-muted-foreground">%{pct}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className={cn("h-full rounded-full",tone==="text-positive"?"bg-positive":tone==="text-negative"?"bg-negative":"bg-warning")} style={{width:`${pct}%`}}/></div></div>}
function AnalystCard({data}:{data:Data}){const a=data.analyst;const d=a?.distribution;return <Card size="sm"><CardHeader><CardTitle>Analist görünümü</CardTitle><CardDescription>{data.symbol} için Yahoo Finance analist derlemesi</CardDescription></CardHeader><CardContent>{d&&d.total>0?<div className="grid gap-4 md:grid-cols-[minmax(0,1fr)_auto]"><div><p className="mb-3 text-sm font-semibold">{d.total} analiste göre</p><div className="grid gap-3"><AnalystBar label="Al" count={d.buy} total={d.total} tone="text-positive"/><AnalystBar label="Tut" count={d.hold} total={d.total} tone="text-warning"/><AnalystBar label="Sat" count={d.sell} total={d.total} tone="text-negative"/></div></div>{a?.targetMean?<div className="grid grid-cols-3 gap-3 self-center border-t pt-3 md:border-l md:border-t-0 md:pl-4 md:pt-0"><div><p className="text-xs text-muted-foreground">Düşük</p><b className="font-mono text-negative">{fmt(a.targetLow)}</b></div><div><p className="text-xs text-muted-foreground">Ortalama hedef</p><b className="font-mono">{fmt(a.targetMean)}</b></div><div><p className="text-xs text-muted-foreground">Yüksek</p><b className="font-mono text-positive">{fmt(a.targetHigh)}</b></div></div>:null}</div>:<p className="text-sm text-muted-foreground">Bu sembol için doğrulanabilir analist dağılımı bulunamadı; tahmin uydurulmadı.</p>}</CardContent></Card>}
function ForecastCard({data}:{data:Data}){const atr=data.technical.values.atr||0;const fib=data.technical.fibonacci;const upside=Math.max(data.technical.resistance,fib.level236||0,data.price+atr);const downside=Math.min(data.technical.support,fib.level618||data.price,data.price-atr);const upPct=((upside/data.price)-1)*100;const downPct=((downside/data.price)-1)*100;return <Card size="sm" className="border-primary/30 bg-primary/5"><CardHeader><CardTitle>Tahmini hareket alanı</CardTitle><CardDescription>Teknik seviyeler + ATR + Fibonacci kesişimi</CardDescription></CardHeader><CardContent className="grid grid-cols-2 gap-3"><div className="rounded-md border border-positive/30 bg-positive/10 p-3"><p className="text-xs text-muted-foreground">Yukarı senaryo</p><b className="font-mono text-lg text-positive">{fmt(upside)}</b><p className="font-mono text-xs text-positive">{upPct>=0?"+":""}{fmt(upPct)}%</p></div><div className="rounded-md border border-negative/30 bg-negative/10 p-3"><p className="text-xs text-muted-foreground">Aşağı risk</p><b className="font-mono text-lg text-negative">{fmt(downside)}</b><p className="font-mono text-xs text-negative">{fmt(downPct)}%</p></div><p className="col-span-2 text-[10px] leading-relaxed text-muted-foreground">Bunlar kesin fiyat tahmini değil, mevcut oynaklık ve teknik kesişimlerden üretilen senaryo sınırlarıdır.</p></CardContent></Card>}
